### ISSUE TITLE
Running out of memory while loading opra trainset

### ISSUE THREAD

**Issue by mkt1412** [Tushar-N/interaction-hotspots#4]
Hi,

Thanks for sharing the source code. While exectuing the command `python eval.py --dset opra --load cv/opra/ckpt_E_20.pth`, my terminal got stuck. After checking the code step by step, it was mainly caused by `hmaps = Parallel(n_jobs=16, verbose=2)(delayed(compute_heatmap)(entry['points'], entry['shape'], kernel_size, transpose) for entry in images)` where heatmaps were being computed and loaded to the memory. The process took over all 32 GB memory and then got killed. 

Any solution to that? Thanks!

**Comment by Tushar-N** [comment]
The code computes all heatmaps and then writes them to disk. You could modify this to write each heatmap as you compute this (i.e. open the h5 file in append mode, and sequentially compute heatmaps instead of using Parallel). I haven't profiled the memory usage of the whole pipeline, but for reference, I ran all models on machines with 252G memory and GPUs with 12G memory.
